package com.ejada.ecommerce.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    ORDER_NOT_FOUND,
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    ACCOUNT_DEACTIVATED,
    INSUFFICIENT_STOCK,
    ORDER_ALREADY_CANCELLED,
    VALIDATION_ERROR,
    UNAUTHORIZED,
    ACCESS_DENIED,
    INTERNAL_SERVER_ERROR
}
